### ISSUE TITLE
symlink issues on OS X

### ISSUE THREAD

**Issue by deepc0py** [gazben/laravel-vue-admin#1]
Both build dev and build prod fail with:
`Linking..
Creating symlink. Target: /home/vagrant/Code/laravel-vue-admin/resources/assets/frontend/dist/assets/css Link: /home/vagrant/Code/laravel-vue-admin/public/assets/css
symlink(): No such file or directory`
I am on OS X Sierra. 

The same output occurs when using the homestead vagrant box.

**Comment by gazben** [comment]
Did you run the `php artisan build:install` command, then the `php artisan build:dev`?
Do you have write permission to the frontend folder?

**Comment by deepc0py** [comment]
Yes, unfortunately still facing the same problem even with `sudo`.
Is there anything else I'm missing? I ran: 
`npm install`
`composer install`
`cp .env.example .env; php artisan key:generate`
  
Here's a screenshot of console output. 
![image](https://cloud.githubusercontent.com/assets/17808066/23777749/949499d2-04eb-11e7-8689-86d59851c6ce.png)

**Comment by gazben** [comment]
That's odd. Somehow in your case the logo.png cannot be found. Try it now, the exceptions will caught during symlink creation. 

You can add your logo later.

**Comment by deepc0py** [comment]
One thing to note before I try: symlinks can't be created for directories on OS X. Just a heads up.

**Comment by deepc0py** [comment]
Works perfectly, thanks for the help!
