### ISSUE TITLE
cp: no such file or directory: assets/*

### ISSUE THREAD

**Issue by kindziora** [gazben/laravel-vue-admin#2]
Hi,

if i try to install:

```composer install``` works
```php artisan build:install```  works
```php artisan build:dev``` does not work :(

i got the error msg that chalk is missing ...then semver and finally shelljs.
So i had to install them manually.
After that i run into this error:

```php artisan build:dev```
`cp: no such file or directory: assets/*`

Maybe its related to webpack.
Could you help me with some advice where to look at?

Thanks!!

**Comment by gazben** [comment]
Hi,

Are you using windows?
What is your npm version?

**Comment by kindziora** [comment]
Hi gazben,

working on ubuntu 16.04 but it seems like the problem does not affect the build process at all. Because i am able to build anyways. So this is maybe not that relevant.

Thanks for your vue-admin implementation using laravel, i'm using it for a current project...

greetings,

alex

**Comment by gazben** [comment]
Thank you, I think I should remove that line, because it's not relevant on any OS.

Gazben
