### ISSUE TITLE
Changes to the my project do not appear in the browser

### ISSUE THREAD

**Issue by Marcosul** [gazben/laravel-vue-admin#4]
Hello! I was able to install and run the project on my machine, however as modifications I do not appear they do not load in the Browser. It looks like the files are cached.

My question should be very simple, but I'm getting a use of laravel and Vue and I can not move forward.

Could you tell me how do I view without browser how modifications I make in my project?

Thank you!!
Marco

**Comment by gazben** [comment]
Hi,
Look in the log that the files are actually emitted. 
If yes, disable the browser cache:
![image](https://cloud.githubusercontent.com/assets/3780285/24766839/25f5d658-1afd-11e7-8e4a-3aab965bf0d3.png)

If no, modify one, or two thing so webpack will re-emit the file.

**Comment by Marcosul** [comment]
Sorry, don't work. When do you say "Webpack",  is this https://webpack.js.org/?

**Comment by Marcosul** [comment]
Maybe I need to use something like "vista-hot-reload-api" in may packge.json, right?

**Comment by Marcosul** [comment]
I had made changes to the project where it caused an error while running the command "php artisan build:watch". Its fine now!
